// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR8prszpxVbMJRxF_rUFi27CW2oh10bEw',
    appId: '1:274163368907:web:79ea4829f4c5e552242c4e',
    messagingSenderId: '274163368907',
    projectId: 'prjectk-f969a',
    authDomain: 'prjectk-f969a.firebaseapp.com',
    storageBucket: 'prjectk-f969a.appspot.com',
    measurementId: 'G-V1QFYXH12E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3HAcfY7Cb_SKmO-J5zhgiKial3iIGbnM',
    appId: '1:274163368907:android:cfbfb54e242287bd242c4e',
    messagingSenderId: '274163368907',
    projectId: 'prjectk-f969a',
    storageBucket: 'prjectk-f969a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlXdYrjOSloRk1oQISlGHDHnbAmyUImk0',
    appId: '1:274163368907:ios:2ce0c9ba19d2e041242c4e',
    messagingSenderId: '274163368907',
    projectId: 'prjectk-f969a',
    storageBucket: 'prjectk-f969a.appspot.com',
    iosClientId: '274163368907-83cb7sbjgee4i53rb9r66vihpq5976t5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlXdYrjOSloRk1oQISlGHDHnbAmyUImk0',
    appId: '1:274163368907:ios:2ce0c9ba19d2e041242c4e',
    messagingSenderId: '274163368907',
    projectId: 'prjectk-f969a',
    storageBucket: 'prjectk-f969a.appspot.com',
    iosClientId: '274163368907-83cb7sbjgee4i53rb9r66vihpq5976t5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
