name: flutter_application_1
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter_custom_clippers: ^2.1.0
  flutter_localizations:
    sdk: flutter 
  shared_preferences: ^2.0.13
  firebase_core: ^2.10.0
  
  


  flutter:
    sdk: flutter 
 
  intl: ^0.17.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  flutter_typeahead: ^4.3.7
  provider: ^6.0.5
  tflite: ^1.1.2
  image: ^4.0.16
  image_picker: ^0.8.7+4
  cupertino_icons: ^1.0.2
  multi_image_picker: ^4.7.14
  page_transition: ^1.1.7+2
  logger: ^1.3.0
  country_picker: ^2.0.20
  firebase_storage: ^11.1.2
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.6.0
  firebase_database: ^10.1.2
  pinput: ^2.2.31
  flutter_staggered_grid_view: ^0.4.0
  vertical_card_pager: ^1.5.0
  url_launcher: ^6.0.9
  webview_flutter: ^3.0.4
  tflite_flutter: ^0.9.5
  



  lottie: ^2.3.2
  flutter_icons: ^1.1.0
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5

  map_location_picker: ^1.1.0
  icon_decoration: ^1.0.1
  http: ^0.13.5
  multi_split_view: ^2.4.0
  scroll_snap_list: ^0.5.1
  flip_card: ^0.7.0
  curved_navigation_bar: ^1.0.3
  cached_network_image: ^3.2.3
  flutter_map: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
    generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
    #uses-material-design: true
    uses-material-design: true
  # To add assets to your application, add an assets section, like this:
    assets:
    - assets/images/logo.png
    - assets/images/P1.png
    - assets/images/login.png
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/4.jpg
    - assets/images/5.jpg
    - assets/images/6.jpg
    - assets/images/7.jpg
    - assets/images/8.jpg
    - assets/images/11.jpg
    - assets/images/12.png
    - assets/images/p1.png
    - assets/images/p22.png
    - assets/images/p33.png
    - assets/images/p44.png
    - assets/images/p55.png
    - assets/images/p66.png
    - assets/images/p77.png
    - assets/images/p88.png
    - assets/images/p99.png
    - assets/images/p10.png
    - assets/images/f1.jpg
    - assets/images/f11.png
    - assets/images/f22.jpg
    - assets/images/f33.jpg
    - assets/images/f44.jpg
    - assets/images/f55.jpg
    - assets/images/f66.jpg
    - assets/images/f77.jpg
    - assets/images/f88.jpg
    - assets/images/f110.jpg
    - assets/images/t1.jpg
    - assets/images/t2.jpg
    - assets/images/t3.jpg
    - assets/images/t4.jpg
    - assets/images/t5.jpg
    - assets/images/t6.jpg
    - assets/images/t7.jpg
    - assets/images/t8.jpg
    - assets/images/t10.jpg
    - assets/images/t11.jpg
    - assets/images/tm.jpg
    - assets/images/v1.png
    - assets/images/v3.png
    - assets/images/v2.png
    - assets/images/v4.png
    - assets/images/v5.png
    - assets/images/v6.png
    - assets/images/v7.png
    - assets/images/v8.png
    - assets/images/v10.png
    - assets/images/v11.png
    - assets/images/v12.png
    - assets/images/v13.png
    - assets/images/v14.png
    - assets/images/ts.jpg
    - assets/images/logo.png
    - assets/images/8.jpg
    - assets/images/image11.jpg
    - assets/images/wall.jpg
    - assets/images/tomato.jpg
    - assets/images/potato.jpg
    - assets/images/rice.jpg
    - assets/images/jowar.jpg
    - assets/images/millet.jpg
    - assets/images/wheat.jpg
    - assets/images/lentils.jpg
    - assets/images/sugarcane.jpg
    - assets/images/maize.jpg
    - assets/images/cotton.jpg
    - assets/images/try3.gif
    - assets/images/try4.webp
    - assets/images/labels.txt
    - assets/images/model_unquant.tflite
    - assets/images/bg_dubai.jpg
    - assets/images/bg_hero_day.jpg
    - assets/images/bg_hero_night.jpg
    - assets/images/bg_london.jpg
    - assets/images/bg_nyc.jpg
    - assets/images/bg_paris.jpg
    - assets/images/empty_cart.png
    - assets/modelNeura.tflite
    - assets/labels2.txt
    - assets/pmfby.png
    - assets/pmksn.jpg
    - assets/kcc.jpg
    - assets/enam.png
    - assets/pkvy.jpg
    - assets/pmksy.jpg
    - assets/msp.jpeg
    - assets/b00k.jpg
    - assets/drne.jpeg
    - assets/bac1.jpeg
    - assets/app.jpg
    - assets/kar.png
    - assets/kerr.jpg
    - assets/tamm.jpg
    - assets/verify.png


    
   
   
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
